name: 'Check Links'
on:
  workflow_call:
    inputs:
      directory:
        required: false
        type: string
      repo_link_ignore_list:
        required: true
        type: string
    secrets:
      PAT:
        required: false
jobs:
  link_check:
    name: 'Link Check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        uses: actions/checkout@v4
        with:
            repository: STRIDES/NIHCloudLab
            path: reusable-workflow-repo
            ref: main

      - name: Link Check
        run: |
          python3 ${GITHUB_WORKSPACE}/reusable-workflow-repo/.github/workflows/check_links.py
        env:
          LINK_IGNORE_LIST: "https://www.sciencedirect.com,https://portlandpress.com,cloud.google.com,aws.amazon.com,https://journals.biologists.com/bio/article-pdf/5/8/1134/1114440/bio020065.pdf,https://onlinelibrary.wiley.com/doi/10.1111/1755-0998.13593,https://www.ensembl.org/,https://github.com/NIGMS/NIGMS-Sandbox/blob/main/README.md,https://github.com/rnaseqprok,https://github.com/rnaseqprok/rnaseqprok/blob/master/CITATIONS.md,https://github.com/NIGMS/NIGMS-Sandbox/blob/main/README.md#available-modules,https://github.com/nf-core/rnaseq/blob/4c27ef5610c87db00c3c5a3eed10b1d161abf575/conf/base.config#L18,https://snakemake.readthedocs.io/en/stable/executor_tutorial/google_lifesciences.html,https://nersc.gitlab.io/development/shifter/how-to-use/,http://bioconductor.org/packages/release/BiocViews.html#___OrgDb,https://www.bioconductor.org/packages/release/bioc/vignettes/methylKit/inst/doc/methylKit.html#4_Annotating_differentially_methylated_bases_or_regions,https://docs.qiime2.org/2024.2/install/native/#qiime-2-metagenome-distribution,https://www.researchgate.net/figure/Diagrams-of-the-BRCA1-and-BRCA2-genes-indicating-the-position-of-pathogenic-variants_fig2_321205153,https://www.fda.gov/drugs/biomarker-qualification-program/about-biomarkers-and-qualification,https://github.com/NIGMS/NIGMS-Sandbox/blob/main/README.md#available-modules,https://www.cambridge.org/highereducation/books/introduction-to-applied-linear-algebra/4D69AF22E38303FE20FFEEFDCE0E7F96#overview,https://doi.org/10.1089/wound.2019.1030"
          PAT: ${{ secrets.PAT }}
