name: 'Lint Notebook'
on:
  push:
  workflow_dispatch:
permissions:
  contents: write
  id-token: write

jobs:
  lint:
    name: 'Linting'
    uses: STRIDES/NIHCloudLab/.github/workflows/notebook-lint.yaml@dev/gh-action
    with:
      directory: .
